### ISSUE TITLE
insert new line between new operator and addchild

### ISSUE THREAD

**Issue by zxcviqekjkasdfl9** [r22n/xmlhx#3]
xmlhx does not print new line like below:
...
addChild(hoge); //<- this adds-child previous field value
var fuga: Fuga = new Fuga(); 
...

i want that xmlhx prints new line into between its.
...
addChild(hoge); //<- this adds-child previous field value
//<- new line is here !
var fuga: Fuga = new Fuga(); 
...

**Comment by r22n** [comment]
check
https://github.com/r22n/xmlhx/pull/4

**Comment by zxcviqekjkasdfl9** [comment]
ok
